### ISSUE TITLE
dhcp-client-identifier no longer tied to mac address and changes from release to release

### ISSUE THREAD

**Issue by datajerk** [open-horizon/ubuntu-classic-image#4]
was with hypriot based image: 1:b8:27:eb:6:7:4d
now:  ff:79:bb:7a:d9:0:2:0:0:ab:11:26:d2:8b:27:71:fd:52:9

This causes issues with dhcp servers that require that the client-id match to get the same lease.

**Comment by michaeldye** [comment]
Fixed in `image 2017-01-14...`  can you confirm?
